using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using LiveryGallery.Localisation;
using LiveryGallery.Models;
using LiveryGallery.Services;

namespace LiveryGallery.ViewModels;

internal sealed partial class AuthorCardRowViewModel(AuthorCard card) : ObservableObject
{
    public AuthorCard Card { get; } = card;

    public string DisplayName => Card.DisplayName;
    public bool IsAutoGenerated => Card.IsAutoGenerated;

    public bool HasAliases => Card.KnownNames.Count > 1;
    public string AliasesText => string.Format(Strings.AuthorCardAliasesFormat, string.Join(", ", Card.KnownNames));

    public bool HasDescription => !string.IsNullOrWhiteSpace(Card.Description);
    public string? Description => Card.Description;

    public bool HasTwitter => Card.TwitterUrl is not null;
    public bool HasYouTube => Card.YouTubeUrl is not null;
    public bool HasAnyLink => HasTwitter || HasYouTube;
    public string? TwitterUrl => Card.TwitterUrl;
    public string? YouTubeUrl => Card.YouTubeUrl;
    public required int LiveriesCount { get; init; }
    public required int FavoritesCount { get; init; }
    public required int DuplicatesCount { get; init; }
    public required int PossibleDuplicatesCount { get; init; }
    public string LiveriesCountText => string.Format(Strings.AuthorCardLiveriesCountFormat, LiveriesCount);
    public string FavoritesCountText => string.Format(Strings.AuthorCardFavoritesCountFormat, FavoritesCount);
    public string DuplicatesCountText => string.Format(Strings.AuthorCardDuplicatesCountFormat, DuplicatesCount);
    public string PossibleDuplicatesCountText => string.Format(Strings.AuthorCardPossibleDuplicatesCountFormat, PossibleDuplicatesCount);

    [RelayCommand]
    private void OpenUrl(string? url)
    {
        if (url is not null) TrustedUrlLauncher.TryOpen(url);
    }
}
