using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using LiveryGallery.Localisation;
using LiveryGallery.Models;
using LiveryGallery.Services;
using System.Collections.ObjectModel;

namespace LiveryGallery.ViewModels;

internal sealed partial class AuthorCardEditViewModel : ObservableObject
{
    private readonly AuthorCardService _authorCardService;
    private readonly string? _editingCardId;
    private readonly Dictionary<string, List<string>> _nameToTags;

    public string Title { get; }
    public bool ShowAutoGeneratedNotice { get; }

    public ObservableCollection<AliasCheckboxViewModel> AvailableAliases { get; } = [];

    [ObservableProperty]
    private string _aliasSearchText = "";

    [ObservableProperty]
    private string? _customName;

    [ObservableProperty]
    private string? _description;

    [ObservableProperty]
    private string? _twitterUrl;

    [ObservableProperty]
    private string? _youTubeUrl;

    [ObservableProperty]
    private bool _hasAliasesError;
    [ObservableProperty]
    private string? _aliasesErrorText;

    [ObservableProperty]
    private bool _hasCustomNameError;
    [ObservableProperty]
    private string? _customNameErrorText;

    [ObservableProperty]
    private bool _hasTwitterError;
    [ObservableProperty]
    private string? _twitterErrorText;

    [ObservableProperty]
    private bool _hasYouTubeError;
    [ObservableProperty]
    private string? _youTubeErrorText;
    public event Action<bool>? CloseRequested;

    public AuthorCard? Result { get; private set; }

    public AuthorCardEditViewModel(
        AuthorCardService authorCardService, List<string> availableAliases,
        Dictionary<string, List<string>> nameToTags, AuthorCard? existingCard, string? preselectedAlias = null)
    {
        _authorCardService = authorCardService;
        _nameToTags = nameToTags;
        _editingCardId = existingCard?.Id;

        Title = existingCard is null ? Strings.AuthorCardNewTitle : Strings.AuthorCardEditTitle;
        ShowAutoGeneratedNotice = existingCard is { IsAutoGenerated: true };
        var selectedAliases = existingCard?.KnownNames.ToHashSet(StringComparer.OrdinalIgnoreCase)
            ?? new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (existingCard is null && preselectedAlias is not null)
            selectedAliases.Add(preselectedAlias);

        foreach (var alias in availableAliases.OrderBy(a => a, StringComparer.OrdinalIgnoreCase))
            AvailableAliases.Add(new AliasCheckboxViewModel(alias) { IsSelected = selectedAliases.Contains(alias) });

        if (existingCard is not null)
        {
            CustomName = existingCard.CustomName;
            Description = existingCard.Description;
            TwitterUrl = existingCard.TwitterUrl;
            YouTubeUrl = existingCard.YouTubeUrl;
        }
    }

    partial void OnAliasSearchTextChanged(string value)
    {
        foreach (var alias in AvailableAliases)
            alias.IsVisible = string.IsNullOrWhiteSpace(value)
                || alias.Name.Contains(value, StringComparison.OrdinalIgnoreCase);
    }

    [RelayCommand]
    private void Save()
    {
        ClearErrors();
        bool hasError = false;

        var selectedAliases = AvailableAliases.Where(a => a.IsSelected).Select(a => a.Name).ToList();

        var selectedTags = selectedAliases
            .SelectMany(name => _nameToTags.TryGetValue(name, out var tags) ? tags : [])
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (selectedAliases.Count == 0)
        {
            HasAliasesError = true;
            AliasesErrorText = Strings.AuthorCardNoAliasesError;
            hasError = true;
        }
        else
        {
            string? conflicting = _authorCardService.FindConflictingIdentityTag(_editingCardId, selectedTags);
            if (conflicting is not null)
            {
                HasAliasesError = true;
                AliasesErrorText = string.Format(Strings.AuthorCardAliasTakenError, conflicting);
                hasError = true;
            }
        }

        string? twitterUrl = NormalizeUrl(TwitterUrl);
        if (twitterUrl is not null && !IsValidTwitterUrl(twitterUrl))
        {
            HasTwitterError = true;
            TwitterErrorText = Strings.AuthorCardInvalidTwitterUrlError;
            hasError = true;
        }

        string? youTubeUrl = NormalizeUrl(YouTubeUrl);
        if (youTubeUrl is not null && !IsValidYouTubeChannelUrl(youTubeUrl))
        {
            HasYouTubeError = true;
            YouTubeErrorText = Strings.AuthorCardInvalidYouTubeUrlError;
            hasError = true;
        }

        if (selectedAliases.Count > 0)
        {
            var candidateName = string.IsNullOrWhiteSpace(CustomName) ? selectedAliases[0] : CustomName.Trim();
            var nameConflict = _authorCardService.FindCardWithDisplayName(_editingCardId, candidateName);
            if (nameConflict is not null)
            {
                HasCustomNameError = true;
                CustomNameErrorText = string.Format(Strings.AuthorCardDisplayNameTakenError, candidateName);
                hasError = true;
            }
        }

        if (hasError) return;

        Result = new AuthorCard
        {
            Id = _editingCardId ?? Guid.NewGuid().ToString("N"),
            IdentityTags = selectedTags,
            KnownNames = selectedAliases,
            CustomName = string.IsNullOrWhiteSpace(CustomName) ? null : CustomName.Trim(),
            Description = string.IsNullOrWhiteSpace(Description) ? null : Description.Trim(),
            TwitterUrl = twitterUrl,
            YouTubeUrl = youTubeUrl,
            IsAutoGenerated = false,
        };
        CloseRequested?.Invoke(true);
    }

    [RelayCommand]
    private void Cancel() => CloseRequested?.Invoke(false);

    private void ClearErrors()
    {
        HasAliasesError = false;
        HasCustomNameError = false;
        HasTwitterError = false;
        HasYouTubeError = false;
    }

    private static string? NormalizeUrl(string? url)
    {
        if (string.IsNullOrWhiteSpace(url)) return null;
        url = url.Trim();
        return url.Contains("://", StringComparison.Ordinal) ? url : $"https://{url}";
    }

    private static bool IsValidTwitterUrl(string url)
    {
        if (!Uri.TryCreate(url, UriKind.Absolute, out var uri)) return false;
        string host = uri.Host.ToLowerInvariant();
        if (!TrustedUrlLauncher.TwitterHosts.Contains(host, StringComparer.OrdinalIgnoreCase))
            return false;

        string[] segments = uri.AbsolutePath.Trim('/').Split('/', StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length != 1) return false;

        string username = segments[0].ToLowerInvariant();
        return username is not (
            "home" or "explore" or "notifications" or "messages" or "search" or "settings"
            or "i" or "intent" or "hashtag" or "share" or "login" or "signup" or "compose" or "about");
    }

    private static bool IsValidYouTubeChannelUrl(string url)
    {
        if (!Uri.TryCreate(url, UriKind.Absolute, out var uri)) return false;
        string host = uri.Host.ToLowerInvariant();
        if (!TrustedUrlLauncher.YouTubeHosts.Contains(host, StringComparer.OrdinalIgnoreCase)) return false;

        string path = uri.AbsolutePath.TrimStart('/');
        return (path.StartsWith('@') && path.Length > 1)
            || HasNonEmptySuffix(path, "channel/")
            || HasNonEmptySuffix(path, "c/")
            || HasNonEmptySuffix(path, "user/");
    }

    private static bool HasNonEmptySuffix(string path, string prefix) =>
        path.StartsWith(prefix, StringComparison.OrdinalIgnoreCase) && path.Length > prefix.Length;
}
