<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
    <Version>1.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
    <AvaloniaResource Remove="Tests\**" />
    <AvaloniaXaml Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LiveryGallery.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="ForzaToolkit.Crypto.Client" Version="1.2.0" />
    <PackageReference Include="ForzaToolkit.Formats" Version="0.43.0" />
    <PackageReference Include="ForzaToolkit.LiveryRender" Version="0.6.1" />
    <PackageReference Include="ForzaToolkit.LiveryRender.Avalonia" Version="0.4.1" />
    <PackageReference Include="Gameloop.Vdf" Version="0.6.2" />
    <PackageReference Include="MarkView.Avalonia" Version="12.2.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localisation\strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localisation\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Themes\" />
  </ItemGroup>

</Project>
