using Avalonia.Controls;
using Avalonia.Input;
using LiveryGallery.Controller;
using LiveryGallery.Localisation;
using LiveryGallery.Models;
using LiveryGallery.Services;
using LiveryGallery.ViewModels;

namespace LiveryGallery.Views;

internal partial class AuthorCardEditDialog : Window
{
    private readonly AuthorCardEditViewModel _viewModel;

    public AuthorCard? Result => _viewModel.Result;

    public AuthorCardEditDialog(
        AuthorCardService authorCardService, List<string> availableAliases,
        Dictionary<string, List<string>> nameToTags, AuthorCard? existingCard, string? preselectedAlias = null)
    {
        InitializeComponent();
        _viewModel = new AuthorCardEditViewModel(authorCardService, availableAliases, nameToTags, existingCard, preselectedAlias);
        DataContext = _viewModel;
        _viewModel.CloseRequested += saved => Close(saved);

        Title = _viewModel.Title;
        TitleBarText.Text = _viewModel.Title;
        TitleText.Text = _viewModel.Title;
        AutoGeneratedNotice.Text = Strings.AuthorCardAutoGeneratedNotice;
        AliasesLabel.Text = Strings.AuthorCardAliasesLabel;
        AliasesHint.Text = Strings.AuthorCardAliasesHint;
        AliasSearchBox.PlaceholderText = Strings.AuthorCardAliasSearchPlaceholder;
        CustomNameLabel.Text = Strings.AuthorCardCustomNameLabel;
        CustomNameBox.PlaceholderText = Strings.AuthorCardCustomNameHint;
        DescriptionLabel.Text = Strings.AuthorCardDescriptionLabel;
        TwitterLabel.Text = Strings.AuthorCardTwitterLabel;
        YouTubeLabel.Text = Strings.AuthorCardYouTubeLabel;
        SaveButton.Content = Strings.ButtonSave;
        CancelButton.Content = Strings.ButtonCancel;
    }

    private void TitleBar_PointerPressed(object? sender, PointerPressedEventArgs e) => this.HandleTitleBarDrag(e);
}
