using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using LiveryGallery.Controller;
using LiveryGallery.Localisation;
using LiveryGallery.Models;
using LiveryGallery.Services;

namespace LiveryGallery.Views;

internal partial class AuthorCardEditDialog : Window
{
    private readonly AuthorCardService _authorCardService;
    private readonly string? _editingCardId;
    private readonly Dictionary<string, List<string>> _nameToTags;
    private readonly List<CheckBox> _aliasCheckBoxes = [];
    public AuthorCard? Result { get; private set; }

    public AuthorCardEditDialog(
        AuthorCardService authorCardService, List<string> availableAliases,
        Dictionary<string, List<string>> nameToTags, AuthorCard? existingCard)
    {
        InitializeComponent();
        _authorCardService = authorCardService;
        _nameToTags = nameToTags;
        _editingCardId = existingCard?.Id;

        string title = existingCard is null ? Strings.AuthorCardNewTitle : Strings.AuthorCardEditTitle;
        Title = title;
        TitleBarText.Text = title;
        TitleText.Text = title;
        if (existingCard is { IsAutoGenerated: true })
        {
            AutoGeneratedNotice.Text = Strings.AuthorCardAutoGeneratedNotice;
            AutoGeneratedNotice.IsVisible = true;
        }
        AliasesLabel.Text = Strings.AuthorCardAliasesLabel;
        AliasesHint.Text = Strings.AuthorCardAliasesHint;
        AliasSearchBox.PlaceholderText = Strings.AuthorCardAliasSearchPlaceholder;
        CustomNameLabel.Text = Strings.AuthorCardCustomNameLabel;
        CustomNameBox.PlaceholderText = Strings.AuthorCardCustomNameHint;
        DescriptionLabel.Text = Strings.AuthorCardDescriptionLabel;
        TwitterLabel.Text = Strings.AuthorCardTwitterLabel;
        YouTubeLabel.Text = Strings.AuthorCardYouTubeLabel;
        SaveButton.Content = Strings.ButtonSave;
        CancelButton.Content = Strings.ButtonCancel;

        var selectedAliases = existingCard?.KnownNames.ToHashSet(StringComparer.OrdinalIgnoreCase)
            ?? new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var alias in availableAliases.OrderBy(a => a, StringComparer.OrdinalIgnoreCase))
        {
            var checkBox = new CheckBox
            {
                Content = alias,
                Tag = alias,
                IsChecked = selectedAliases.Contains(alias),
                Margin = new Avalonia.Thickness(0, 3),
            };
            _aliasCheckBoxes.Add(checkBox);
            AliasesPanel.Children.Add(checkBox);
        }

        if (existingCard is not null)
        {
            CustomNameBox.Text = existingCard.CustomName;
            DescriptionBox.Text = existingCard.Description;
            TwitterBox.Text = existingCard.TwitterUrl;
            YouTubeBox.Text = existingCard.YouTubeUrl;
        }
    }

    private void TitleBar_PointerPressed(object? sender, PointerPressedEventArgs e) => this.HandleTitleBarDrag(e);

    private void AliasSearchBox_TextChanged(object? sender, TextChangedEventArgs e)
    {
        string query = AliasSearchBox.Text ?? "";
        foreach (var checkBox in _aliasCheckBoxes)
        {
            string alias = (string)checkBox.Tag!;
            checkBox.IsVisible = string.IsNullOrWhiteSpace(query)
                || alias.Contains(query, StringComparison.OrdinalIgnoreCase);
        }
    }

    private void SaveButton_Click(object? sender, RoutedEventArgs e)
    {
        ClearErrors();
        bool hasError = false;

        var selectedAliases = _aliasCheckBoxes
            .Where(cb => cb.IsChecked == true)
            .Select(cb => (string)cb.Tag!)
            .ToList();

        var selectedTags = selectedAliases
            .SelectMany(name => _nameToTags.TryGetValue(name, out var tags) ? tags : [])
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (selectedAliases.Count == 0)
        {
            ShowError(AliasesErrorText, Strings.AuthorCardNoAliasesError);
            hasError = true;
        }
        else
        {
            string? conflicting = _authorCardService.FindConflictingIdentityTag(_editingCardId, selectedTags);
            if (conflicting is not null)
            {
                ShowError(AliasesErrorText, string.Format(Strings.AuthorCardAliasTakenError, conflicting));
                hasError = true;
            }
        }

        string? twitterUrl = NormalizeUrl(TwitterBox.Text);
        if (twitterUrl is not null && !IsValidTwitterUrl(twitterUrl))
        {
            ShowError(TwitterErrorText, Strings.AuthorCardInvalidTwitterUrlError);
            hasError = true;
        }

        string? youTubeUrl = NormalizeUrl(YouTubeBox.Text);
        if (youTubeUrl is not null && !IsValidYouTubeChannelUrl(youTubeUrl))
        {
            ShowError(YouTubeErrorText, Strings.AuthorCardInvalidYouTubeUrlError);
            hasError = true;
        }

        string? displayNameError = null;
        if (selectedAliases.Count > 0)
        {
            var candidateName = string.IsNullOrWhiteSpace(CustomNameBox.Text)
                ? selectedAliases[0]
                : CustomNameBox.Text.Trim();
            var nameConflict = _authorCardService.FindCardWithDisplayName(_editingCardId, candidateName);
            if (nameConflict is not null)
                displayNameError = string.Format(Strings.AuthorCardDisplayNameTakenError, candidateName);
        }

        if (displayNameError is not null)
        {
            ShowError(CustomNameErrorText, displayNameError);
            hasError = true;
        }

        if (hasError) return;

        var candidate = new AuthorCard
        {
            Id = _editingCardId ?? Guid.NewGuid().ToString("N"),
            IdentityTags = selectedTags,
            KnownNames = selectedAliases,
            CustomName = string.IsNullOrWhiteSpace(CustomNameBox.Text) ? null : CustomNameBox.Text.Trim(),
            Description = string.IsNullOrWhiteSpace(DescriptionBox.Text) ? null : DescriptionBox.Text.Trim(),
            TwitterUrl = twitterUrl,
            YouTubeUrl = youTubeUrl,
            IsAutoGenerated = false,
        };

        Result = candidate;
        Close(true);
    }

    private static string? NormalizeUrl(string? url)
    {
        if (string.IsNullOrWhiteSpace(url)) return null;
        url = url.Trim();
        return url.Contains("://", StringComparison.Ordinal) ? url : $"https://{url}";
    }

    private static bool IsValidTwitterUrl(string url)
    {
        if (!Uri.TryCreate(url, UriKind.Absolute, out var uri)) return false;
        string host = uri.Host.ToLowerInvariant();
        if (!TrustedUrlLauncher.TwitterHosts.Contains(host, StringComparer.OrdinalIgnoreCase))
            return false;

        string[] segments = uri.AbsolutePath.Trim('/').Split('/', StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length != 1) return false;

        string username = segments[0].ToLowerInvariant();
        return username is not (
            "home" or "explore" or "notifications" or "messages" or "search" or "settings"
            or "i" or "intent" or "hashtag" or "share" or "login" or "signup" or "compose" or "about");
    }

    private static bool IsValidYouTubeChannelUrl(string url)
    {
        if (!Uri.TryCreate(url, UriKind.Absolute, out var uri)) return false;
        string host = uri.Host.ToLowerInvariant();
        if (!TrustedUrlLauncher.YouTubeHosts.Contains(host, StringComparer.OrdinalIgnoreCase)) return false;

        string path = uri.AbsolutePath.TrimStart('/');
        return (path.StartsWith('@') && path.Length > 1)
            || HasNonEmptySuffix(path, "channel/")
            || HasNonEmptySuffix(path, "c/")
            || HasNonEmptySuffix(path, "user/");
    }

    private static bool HasNonEmptySuffix(string path, string prefix) =>
        path.StartsWith(prefix, StringComparison.OrdinalIgnoreCase) && path.Length > prefix.Length;

    private static void ShowError(TextBlock target, string message)
    {
        target.Text = message;
        target.IsVisible = true;
    }

    private void ClearErrors()
    {
        AliasesErrorText.IsVisible = false;
        CustomNameErrorText.IsVisible = false;
        TwitterErrorText.IsVisible = false;
        YouTubeErrorText.IsVisible = false;
    }

    private void CancelButton_Click(object? sender, RoutedEventArgs e) => Close(false);
}
