using LiveryGallery.Configuration;
using LiveryGallery.Models;
using System.Text.Json;

namespace LiveryGallery.Services;

internal readonly record struct AuthorObservation(string AuthorRaw, string? IdentityTagHex, DateTime? DownloadDate);

internal class AuthorCardService
{
    private static readonly string _path = Path.Combine(AppSettings.BaseCachePath, "author_cards.json");
    private readonly Lock _lock = new();
    private List<AuthorCard> _cards = [];
    private Dictionary<string, AuthorCard> _identityTagIndex = new(StringComparer.OrdinalIgnoreCase);

    public AuthorCardService() => Load();

    public IReadOnlyList<AuthorCard> GetAll()
    {
        lock (_lock) return [.. _cards];
    }

    public string ResolveDisplayName(string rawAuthor, string? identityTagHex)
    {
        lock (_lock)
        {
            if (identityTagHex is not null && _identityTagIndex.TryGetValue(identityTagHex, out var card))
                return card.DisplayName;
        }
        return rawAuthor;
    }

    public AuthorCard? FindCardForIdentityTag(string identityTagHex)
    {
        lock (_lock)
            return _identityTagIndex.TryGetValue(identityTagHex, out var card) ? card : null;
    }

    public string? FindConflictingIdentityTag(string? excludeCardId, IEnumerable<string> identityTags)
    {
        lock (_lock)
            return FindConflictingIdentityTagNoLock(excludeCardId, identityTags);
    }

    public AuthorCard? FindCardWithDisplayName(string? excludeCardId, string displayName)
    {
        lock (_lock)
            return _cards.FirstOrDefault(c =>
                c.Id != excludeCardId && string.Equals(c.DisplayName, displayName, StringComparison.OrdinalIgnoreCase));
    }

    public async Task<bool> TrySave(AuthorCard card)
    {
        card = card with { IsAutoGenerated = false };
        lock (_lock)
        {
            if (FindConflictingIdentityTagNoLock(card.Id, card.IdentityTags) is not null)
                return false;
            if (_cards.Any(c => c.Id != card.Id
                && string.Equals(c.DisplayName, card.DisplayName, StringComparison.OrdinalIgnoreCase)))
                return false;

            _cards.RemoveAll(c => c.Id == card.Id);
            _cards.Add(card);
            RebuildIndexNoLock();
        }
        return await SaveAsync();
    }

    public async Task Delete(string cardId)
    {
        lock (_lock)
        {
            _cards.RemoveAll(c => c.Id == cardId);
            RebuildIndexNoLock();
        }
        await SaveAsync();
    }

    public void ReconcileAutoCards(IEnumerable<AuthorObservation> observations)
    {
        var observationList = observations as IReadOnlyCollection<AuthorObservation> ?? [.. observations];

        var byTag = observationList
            .Where(o => !string.IsNullOrEmpty(o.IdentityTagHex))
            .GroupBy(o => o.IdentityTagHex!, StringComparer.OrdinalIgnoreCase);

        bool changed = false;

        lock (_lock)
        {
            if (_cards.Any(c => c.IdentityTags.Count == 0))
            {
                var tagsByName = observationList
                    .Where(o => !string.IsNullOrEmpty(o.IdentityTagHex))
                    .GroupBy(o => o.AuthorRaw, StringComparer.OrdinalIgnoreCase)
                    .ToDictionary(
                        g => g.Key,
                        g => g.Select(o => o.IdentityTagHex!).Distinct(StringComparer.OrdinalIgnoreCase).ToList(),
                        StringComparer.OrdinalIgnoreCase);

                for (int i = 0; i < _cards.Count; i++)
                {
                    var orphan = _cards[i];
                    if (orphan.IdentityTags.Count > 0) continue;

                    var candidateTags = orphan.KnownNames
                        .SelectMany(name => tagsByName.TryGetValue(name, out var tags) ? tags : [])
                        .Distinct(StringComparer.OrdinalIgnoreCase)
                        .Where(tag => !_identityTagIndex.ContainsKey(tag))
                        .ToList();
                    if (candidateTags.Count != 1) continue;

                    _cards[i] = orphan with { IdentityTags = candidateTags };
                    changed = true;
                }

                if (changed) RebuildIndexNoLock();
            }

            foreach (var group in byTag)
            {
                string tag = group.Key;
                var namesChronological = group
                    .Select(o => (o.AuthorRaw, Date: o.DownloadDate ?? DateTime.MinValue))
                    .GroupBy(x => x.AuthorRaw, StringComparer.OrdinalIgnoreCase)
                    .Select(g => (Name: g.Key, LatestDate: g.Max(x => x.Date)))
                    .OrderBy(x => x.LatestDate)
                    .Select(x => x.Name)
                    .ToList();

                if (namesChronological.Count == 0) continue;

                var existing = _identityTagIndex.GetValueOrDefault(tag);

                if (existing is null)
                {
                    if (namesChronological.Count < 2) continue;

                    var created = new AuthorCard
                    {
                        Id = Guid.NewGuid().ToString("N"),
                        IdentityTags = [tag],
                        KnownNames = namesChronological,
                        CustomName = null,
                        IsAutoGenerated = true,
                    };
                    _cards.Add(created);
                    changed = true;
                }
                else
                {
                    var mergedNames = existing.KnownNames
                        .Concat(namesChronological)
                        .Distinct(StringComparer.OrdinalIgnoreCase)
                        .ToList();
                    if (mergedNames.Count != existing.KnownNames.Count)
                    {
                        var updated = existing with
                        {
                            KnownNames = mergedNames,
                            CustomName = existing.IsAutoGenerated ? null : existing.CustomName,
                        };
                        _cards[_cards.IndexOf(existing)] = updated;
                        changed = true;
                    }
                }
            }

            if (changed) RebuildIndexNoLock();
        }

        if (changed) Save();
    }

    private string? FindConflictingIdentityTagNoLock(string? excludeCardId, IEnumerable<string> identityTags)
    {
        foreach (var tag in identityTags)
        {
            if (_identityTagIndex.TryGetValue(tag, out var existing) && existing.Id != excludeCardId)
                return tag;
        }
        return null;
    }

    private void RebuildIndexNoLock()
    {
        var usedTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var validCards = new List<AuthorCard>(_cards.Count);
        var seenDisplayNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        bool anyConflictRemoved = false;

        foreach (var card in _cards)
        {
            if (card.IdentityTags.Count == 0)
            {
                if (!seenDisplayNames.Add(card.DisplayName))
                {
                    var untaggedResolved = card with { CustomName = null };
                    if (!seenDisplayNames.Add(untaggedResolved.DisplayName)) continue;
                    validCards.Add(untaggedResolved);
                }
                else
                {
                    validCards.Add(card);
                }
                continue;
            }

            List<string>? deduped = null;
            foreach (var tag in card.IdentityTags)
            {
                if (usedTags.Contains(tag))
                {
                    anyConflictRemoved = true;
                    continue;
                }
                usedTags.Add(tag);
                (deduped ??= []).Add(tag);
            }

            if (deduped is null || deduped.Count == 0)
            {
                anyConflictRemoved = true;
                continue;
            }

            var resolved = deduped.Count == card.IdentityTags.Count ? card : card with { IdentityTags = deduped };
            if (!seenDisplayNames.Add(resolved.DisplayName))
            {
                anyConflictRemoved = true;
                resolved = resolved with { CustomName = null };
                if (!seenDisplayNames.Add(resolved.DisplayName))
                {
                    continue;
                }
            }

            validCards.Add(resolved);
        }

        if (anyConflictRemoved)
        {
            AppLogger.LogError(
                "Author cards file had conflicting identity tags across cards, auto-resolved on load",
                new InvalidDataException("Duplicate identity tag across author cards"));
            AtomicFile.TryBackupFile(_path, ".before-auto-fix");
            _cards = validCards;
            Save();
        }

        var index = new Dictionary<string, AuthorCard>(StringComparer.OrdinalIgnoreCase);
        foreach (var card in validCards)
            foreach (var tag in card.IdentityTags)
                index[tag] = card;
        _identityTagIndex = index;
    }

    private void Save()
    {
        try
        {
            List<AuthorCard> snapshot;
            lock (_lock) snapshot = [.. _cards];
            string json = JsonSerializer.Serialize(snapshot, JsonSettings.DefaultOptions);
            PersistenceManager.Schedule(_path, json);
        }
        catch (Exception ex)
        {
            AppLogger.LogError("Failed to serialise author cards", ex);
        }
    }

    private async Task<bool> SaveAsync()
    {
        try
        {
            List<AuthorCard> snapshot;
            lock (_lock) snapshot = [.. _cards];
            string json = JsonSerializer.Serialize(snapshot, JsonSettings.DefaultOptions);
            return await PersistenceManager.SaveNowAsync(_path, json);
        }
        catch (Exception ex)
        {
            AppLogger.LogError("Failed to serialise author cards", ex);
            return false;
        }
    }

    private void Load()
    {
        try
        {
            if (File.Exists(_path))
            {
                string json = File.ReadAllText(_path);
                var data = JsonSerializer.Deserialize<List<AuthorCard>>(json, JsonSettings.DefaultOptions);
                if (data != null)
                {
                    _cards = MigrateLegacyAliases(json, data);
                    RebuildIndexNoLock();
                }
            }
        }
        catch (Exception ex)
        {
            AppLogger.LogError("Failed to load author cards", ex);
            AtomicFile.TryBackupCorruptedFile(_path);
        }
    }

    private static List<AuthorCard> MigrateLegacyAliases(string json, List<AuthorCard> cards)
    {
        if (cards.All(c => c.KnownNames.Count > 0)) return cards;

        Dictionary<string, List<string>>? legacyAliasesById = null;
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind != JsonValueKind.Array) return cards;

            foreach (var element in doc.RootElement.EnumerateArray())
            {
                if (!element.TryGetProperty("Id", out var idProp) || idProp.ValueKind != JsonValueKind.String) continue;
                if (!element.TryGetProperty("Aliases", out var aliasesProp) || aliasesProp.ValueKind != JsonValueKind.Array) continue;

                var names = aliasesProp.EnumerateArray()
                    .Where(a => a.ValueKind == JsonValueKind.String)
                    .Select(a => a.GetString()!)
                    .Where(a => !string.IsNullOrWhiteSpace(a))
                    .ToList();
                if (names.Count == 0) continue;

                (legacyAliasesById ??= new(StringComparer.Ordinal))[idProp.GetString()!] = names;
            }
        }
        catch (JsonException ex)
        {
            AppLogger.LogError("Failed to scan author_cards.json for legacy Aliases during migration", ex);
            return cards;
        }

        if (legacyAliasesById is null || legacyAliasesById.Count == 0) return cards;

        return [.. cards.Select(c =>
            c.KnownNames.Count == 0 && legacyAliasesById.TryGetValue(c.Id, out var names)
                ? c with { KnownNames = names }
                : c)];
    }
}
