namespace LiveryGallery.Models;

internal record AuthorCard
{
    public required string Id { get; init; }
    public IReadOnlyList<string> IdentityTags { get; init; } = [];
    public IReadOnlyList<string> KnownNames { get; init; } = [];
    public string? CustomName { get; init; }
    public string? Description { get; init; }
    public string? TwitterUrl { get; init; }
    public string? YouTubeUrl { get; init; }
    public bool IsAutoGenerated { get; init; }

    public string DisplayName =>
        !string.IsNullOrWhiteSpace(CustomName) ? CustomName
        : KnownNames.Count > 0 ? KnownNames[^1]
        : "?";
}
